# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    cache: default

    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media'

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"

    filter_sets:
        cache: ~
        default_thumb:
            quality: 100
            filters:
                thumbnail: { size: [150, 85], mode: outbound }
        tiny_thumb:
            quality: 100
            filters:
                thumbnail: { size: [32, 32], mode: outbound }
