security:
    encoders:
        EryseBlog\Security\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    providers:
        app_user_provider:
            memory:
                users:
                    raito: { password: '$argon2id$v=19$m=65536,t=4,p=1$zGIVjhwf/5jfzqVeYG4GyA$cVwclec+f6+bLN8Wo2fBBNJ3XU0atnuDZxEjR2kWnWo', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - EryseBlog\Security\Authenticator\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
