version: "3.5"
services:

  # nginx web server
  # ------------------------------------------------------------------------------------------------------------------
  webserver:
    ports:
      - "8000:80"

  # PHP
  # ------------------------------------------------------------------------------------------------------------------
  php:
    ports:
      - "9001:9000"

  # Postgres
  # ------------------------------------------------------------------------------------------------------------------
  database:
    ports:
      - "5490:5432"

  # Redis
  # ------------------------------------------------------------------------------------------------------------------
  redis:
    ports:
      - "6379:6379"
